### ISSUE TITLE
[Bug]: v2rayn升级失败

### ISSUE THREAD

**Issue by dong-lufei** [DoveBoy/Apps#6]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.
- [X] I have verified that I am using the latest version of Scoop and corresponding bucket.

### Package Name

v2rayn

### Expected/Current Behaviour

$ scoop update v2rayn
v2rayn: 6.17 -> 6.19
Updating one outdated app:
Updating 'v2rayn' (6.17 -> 6.19)
Downloading new version
Starting download with aria2 ...
Download: Download Results:
Download: gid   |stat|avg speed  |path/URI
Download: ======+====+===========+=======================================================
Download: 482f59|OK  |   469KiB/s|D:/scoop_user_apps/cache/v2rayn#6.19#https_github.com_2dust_v2rayN_releases_download_6.19_v2rayN.zip
Download: Status Legend:
Download: (OK):download completed.
Checking hash of v2rayN.zip ... ERROR Hash check failed!
App:         apps/v2rayn
URL:         https://github.com/2dust/v2rayN/releases/download/6.19/v2rayN.zip
First bytes: 50 4B 03 04 14 00 00 00
Expected:    aa67d6126ef0dc222ee0020c5af511da255ee55c915a1df8004e21f8c326bbdc
Actual:      6ffd1e79c2e9172d01be19f518a07442975bc9622b8be673c685c4b739ec04fe

Please try again or create a new issue by using the following link and paste your console output:
https://gitee.com/donglufei/Apps

### Steps to Reproduce

```console
scoop update v2rayn
```

### Possible Solution

试了3次都失败

### Scoop and Buckets Version

```console
$ scoop --version
Current Scoop version:
v0.3.1 - Released at 2022-11-15
```

### Scoop Config

```console
$ scoop config

aria2-enabled                   : True
aria2-split                     : 32
aria2-max-connection-per-server : 16
aria2-min-split-size            : 1M
aria2-warning-enabled           : False
aria2-retry-wait                : 4
aria2-cnabled                   : True
last_update                     : 2023/3/27 10:10:48
scoop_repo                      : https://gitee.com/scoop-bucket/scoop
scoop_branch                    : master
```

### PowerShell Version

```console
$ $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.3.2
PSEdition                      Core
GitCommitId                    7.3.2
OS                             Microsoft Windows 10.0.22000
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by DoveBoy** [comment]
修改正确的hash或者使用`scoop update * -s`忽略hash检查
